name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Simple deployment for existing setup
          # Assuming the app is already at /var/www/mga-portal
          cd /var/www/mga-portal
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm ci
          
          # Run database migrations
          npx prisma migrate deploy
          
          # Build the application
          npm run build
          
          # Restart PM2 process
          pm2 restart mga-portal || pm2 start npm --name "mga-portal" -- start
          
          # Save PM2 process list
          pm2 save