name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy via SSH
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USERNAME }}
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        
        # Deploy
        ssh -o StrictHostKeyChecking=no $USER@$HOST 'bash -s' << 'ENDSSH'
          set -e
          echo "Starting deployment..."
          
          # Navigate to app directory
          cd /var/www/mga-portal || { echo "App directory not found!"; exit 1; }
          
          # Pull latest changes
          echo "Pulling latest changes..."
          git pull origin main
          
          # Install dependencies
          echo "Installing dependencies..."
          npm ci
          
          # Run database migrations
          echo "Running database migrations..."
          npx prisma migrate deploy
          
          # Build the application
          echo "Building application..."
          npm run build
          
          # Restart PM2 process
          echo "Restarting application..."
          pm2 restart mga-portal || pm2 start npm --name "mga-portal" -- start
          
          # Save PM2 process list
          pm2 save
          
          echo "Deployment completed successfully!"
        ENDSSH